### ISSUE TITLE
Video not found from Dailymotion Channel

### ISSUE THREAD

**Issue by ghost** [mecha-cms/extend.plugin.dailymotion#1]
Hi @tovic  ,

Can you please check Dailymotion videos again, because it seems that videos can not be found.

I removed all "medie embed" plugins in Ckeditor and just used the video URL in the editor. In the frontend under https://mechacms.wpzweinull.ch/projekte/eigene-projekte#stage:dailymotion-video-channel I am shown that allegedly permissions for the video are missing.

So I also turned to the support. Maybe it can still be due to the plugin?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
How is it like when a video channel converted into embed code? The plugin currently support individual video like the [YouTube](https://github.com/mecha-cms/extend.plugin.youtube) does because I cannot find a way to embed video channel from the official website of each services.

**Comment by ghost** [comment]
No, it is embedded with me an individual video. I only took the video URL from Dailymotion and placed it in the Ckeditor.

Let's see what the support will say, because something must be there.

Otherwise, it works somewhere else with me with the individual videos of Dailymotion.

I just thought, maybe it's the plugin, so my question to you.

**Comment by ghost** [comment]
Thanks, Tovic! Dailymotion-Video with URL Embed now worked!
